-- Database Optimization Script for omega_optimization.db
-- Generated by Claude Code Database Optimization Agent
-- Date: 2025-08-13

-- =================================================================
-- PHASE 1: CRITICAL PERFORMANCE SETTINGS
-- =================================================================

-- Enable foreign key constraints for data integrity
PRAGMA foreign_keys = ON;

-- Switch to WAL mode for better concurrent access and performance
PRAGMA journal_mode = WAL;

-- Set synchronous to NORMAL for better performance while maintaining safety
PRAGMA synchronous = NORMAL;

-- Increase cache size for better analytical performance (40MB cache)
PRAGMA cache_size = 10000;

-- Use memory for temporary storage
PRAGMA temp_store = MEMORY;

-- =================================================================
-- PHASE 2: STRATEGIC INDEXING
-- =================================================================

-- Index for trial parameter queries (most common operation)
-- Speeds up queries filtering by parameter name and value
CREATE INDEX IF NOT EXISTS ix_trial_params_name_value 
ON trial_params(param_name, param_value);

-- Index for time-based trial queries
CREATE INDEX IF NOT EXISTS ix_trials_datetime_start 
ON trials(datetime_start);

-- Index for trial state and datetime queries (common filtering pattern)
CREATE INDEX IF NOT EXISTS ix_trials_state_datetime 
ON trials(state, datetime_start);

-- Index for trial value optimization queries
CREATE INDEX IF NOT EXISTS ix_trial_values_objective_value 
ON trial_values(objective, value DESC);

-- Composite index for common join patterns
CREATE INDEX IF NOT EXISTS ix_trials_study_state 
ON trials(study_id, state);

-- Index for parameter name frequency analysis
CREATE INDEX IF NOT EXISTS ix_trial_params_name 
ON trial_params(param_name);

-- =================================================================
-- PHASE 3: ANALYTICAL VIEWS FOR COMMON QUERIES
-- =================================================================

-- View for best trial parameters (most frequently accessed data)
CREATE VIEW IF NOT EXISTS v_best_trial_params AS
SELECT 
    tp.param_name,
    tp.param_value,
    tv.value as objective_value,
    t.datetime_complete,
    t.trial_id
FROM trial_params tp
JOIN trials t ON tp.trial_id = t.trial_id
JOIN trial_values tv ON t.trial_id = tv.trial_id
WHERE tv.trial_id = (
    SELECT trial_id 
    FROM trial_values 
    WHERE objective = 0 
    ORDER BY value DESC 
    LIMIT 1
);

-- View for trial performance summary
CREATE VIEW IF NOT EXISTS v_trial_summary AS
SELECT 
    t.trial_id,
    t.number,
    t.state,
    t.datetime_start,
    t.datetime_complete,
    tv.value as objective_value,
    (julianday(t.datetime_complete) - julianday(t.datetime_start)) * 86400 as duration_seconds
FROM trials t
LEFT JOIN trial_values tv ON t.trial_id = tv.trial_id AND tv.objective = 0
WHERE t.state = 'COMPLETE';

-- View for parameter correlation analysis
CREATE VIEW IF NOT EXISTS v_parameter_stats AS
SELECT 
    param_name,
    COUNT(*) as trial_count,
    AVG(param_value) as avg_value,
    MIN(param_value) as min_value,
    MAX(param_value) as max_value,
    AVG(tv.value) as avg_objective
FROM trial_params tp
JOIN trial_values tv ON tp.trial_id = tv.trial_id
GROUP BY param_name
ORDER BY avg_objective DESC;

-- =================================================================
-- PHASE 4: OPTIMIZATION AND ANALYSIS
-- =================================================================

-- Update query planner statistics
ANALYZE;

-- =================================================================
-- VERIFICATION QUERIES
-- =================================================================

-- Check foreign key constraints are enabled
-- PRAGMA foreign_keys;

-- Check journal mode is WAL
-- PRAGMA journal_mode;

-- List all indexes to verify creation
-- SELECT name, sql FROM sqlite_master WHERE type = 'index' AND name LIKE 'ix_%';

-- Check database integrity
-- PRAGMA integrity_check;