-- Database Maintenance and Monitoring Script for omega_optimization.db
-- Generated by Claude Code Database Optimization Agent
-- Date: 2025-08-13

-- =================================================================
-- PERSISTENT SETTINGS (Run these before each session)
-- =================================================================

-- Enable foreign key constraints (must be set per connection)
PRAGMA foreign_keys = ON;

-- Set optimal memory settings
PRAGMA cache_size = 10000;  -- 40MB cache
PRAGMA temp_store = MEMORY;

-- =================================================================
-- PERFORMANCE MONITORING QUERIES
-- =================================================================

-- Query 1: Database size and statistics
.print "=== DATABASE STATISTICS ==="
SELECT 
    'Total Pages' as metric, page_count as value FROM PRAGMA_PAGE_COUNT()
UNION ALL
SELECT 
    'Page Size (bytes)', page_size FROM PRAGMA_PAGE_SIZE()
UNION ALL
SELECT 
    'Database Size (KB)', (page_count * page_size) / 1024 FROM PRAGMA_PAGE_COUNT(), PRAGMA_PAGE_SIZE()
UNION ALL
SELECT 
    'Foreign Keys Enabled', foreign_keys FROM PRAGMA_FOREIGN_KEYS()
UNION ALL
SELECT 
    'Journal Mode', journal_mode FROM PRAGMA_JOURNAL_MODE();

-- Query 2: Index usage analysis
.print ""
.print "=== INDEX ANALYSIS ==="
SELECT 
    name as index_name,
    CASE 
        WHEN name LIKE 'ix_%' THEN 'Custom'
        WHEN name LIKE 'sqlite_autoindex_%' THEN 'Automatic'
        ELSE 'Other'
    END as index_type
FROM sqlite_master 
WHERE type = 'index' 
ORDER BY index_type, name;

-- Query 3: Table row counts and sizes
.print ""
.print "=== TABLE STATISTICS ==="
SELECT 
    name as table_name,
    (SELECT COUNT(*) FROM studies) as row_count
FROM sqlite_master 
WHERE type = 'table' AND name = 'studies'
UNION ALL
SELECT 
    'trials',
    (SELECT COUNT(*) FROM trials)
UNION ALL
SELECT 
    'trial_params',
    (SELECT COUNT(*) FROM trial_params)
UNION ALL
SELECT 
    'trial_values',
    (SELECT COUNT(*) FROM trial_values)
ORDER BY table_name;

-- Query 4: Current optimization trials summary
.print ""
.print "=== OPTIMIZATION TRIALS SUMMARY ==="
SELECT 
    COUNT(*) as total_trials,
    COUNT(CASE WHEN state = 'COMPLETE' THEN 1 END) as completed_trials,
    COUNT(CASE WHEN state = 'RUNNING' THEN 1 END) as running_trials,
    COUNT(CASE WHEN state = 'FAILED' THEN 1 END) as failed_trials,
    MIN(datetime_start) as first_trial,
    MAX(datetime_complete) as last_completion
FROM trials;

-- Query 5: Best performing parameters
.print ""
.print "=== BEST TRIAL PARAMETERS ==="
SELECT * FROM v_best_trial_params ORDER BY param_name;

-- Query 6: Parameter optimization trends
.print ""
.print "=== PARAMETER STATISTICS ==="
SELECT * FROM v_parameter_stats LIMIT 10;

-- =================================================================
-- MAINTENANCE PROCEDURES
-- =================================================================

-- Monthly maintenance routine
-- VACUUM; -- Uncomment to reclaim space (run manually when needed)
-- REINDEX; -- Uncomment to rebuild indexes (run manually when needed)
-- ANALYZE; -- Update query planner statistics (safe to run regularly)

ANALYZE;