#!/usr/bin/env python3
"""
Update iOS Certificate Pinning Manager with production certificates
"""

import json
import click
import hashlib
from pathlib import Path
from typing import Dict, List
import requests
import ssl
import socket
from cryptography import x509
from cryptography.hazmat.primitives import serialization

class IOSCertificatePinningUpdater:
    """Updates iOS certificate pinning configuration with production certificates"""
    
    def __init__(self):
        self.ssl_dir = Path("./ssl")
        self.ios_dir = Path("./ios/OmegaApp_Clean")
        
    def extract_certificate_fingerprints(self, cert_path: str) -> Dict[str, str]:
        """Extract certificate fingerprints for pinning"""
        
        fingerprints = {}
        
        try:
            with open(cert_path, 'rb') as f:
                cert_data = f.read()
            
            cert = x509.load_pem_x509_certificate(cert_data)
            
            # Certificate SHA256 fingerprint
            cert_fingerprint = hashlib.sha256(cert_data).hexdigest()
            fingerprints['certificate_sha256'] = cert_fingerprint
            
            # Public key SHA256 fingerprint
            public_key = cert.public_key()
            public_key_der = public_key.public_key_bytes(
                encoding=serialization.Encoding.DER,
                format=serialization.PublicFormat.SubjectPublicKeyInfo
            )
            public_key_fingerprint = hashlib.sha256(public_key_der).hexdigest()
            fingerprints['public_key_sha256'] = public_key_fingerprint
            
            # SPKI fingerprint
            spki_fingerprint = hashlib.sha256(public_key_der).hexdigest()
            fingerprints['spki_sha256'] = spki_fingerprint
            
            return fingerprints
            
        except Exception as e:
            click.echo(f"❌ Failed to extract fingerprints: {e}")
            return {}
    
    def download_certificate_from_domain(self, domain: str, port: int = 443) -> bytes:
        """Download certificate from domain"""
        
        try:
            context = ssl.create_default_context()
            context.check_hostname = False
            context.verify_mode = ssl.CERT_NONE
            
            with socket.create_connection((domain, port), timeout=10) as sock:
                with context.wrap_socket(sock, server_hostname=domain) as ssock:
                    der_cert = ssock.getpeercert(binary_form=True)
                    return der_cert
                    
        except Exception as e:
            click.echo(f"❌ Failed to download certificate from {domain}: {e}")
            return b""
    
    def generate_swift_pinning_code(self, fingerprints: Dict[str, str], domain: str) -> str:
        """Generate Swift code for certificate pinning"""
        
        swift_code = f"""
// Production certificate pinning for {domain}
// Auto-generated by update_ios_pinning.py

private func setupProductionCertificatePinning() {{
    // Production Akash Network Configuration
    let productionConfig = PinningConfiguration(
        domain: "{domain}",
        publicKeyHashes: [
            "{fingerprints.get('public_key_sha256', '')}",
            "{fingerprints.get('spki_sha256', '')}"
        ],
        certificateHashes: [
            "{fingerprints.get('certificate_sha256', '')}"
        ],
        allowSelfSigned: false,  // Production uses CA-signed certificates
        requireCertificatePinning: true,
        environment: .production
    )
    pinningConfigurations[productionConfig.domain] = productionConfig
    
    AppLogger.shared.info("Production certificate pinning configured for: {domain}", category: .security)
}}

// Certificate fingerprints for manual verification:
// Certificate SHA256: {fingerprints.get('certificate_sha256', '')}
// Public Key SHA256:  {fingerprints.get('public_key_sha256', '')}
// SPKI SHA256:        {fingerprints.get('spki_sha256', '')}
"""
        return swift_code
    
    def update_ssl_pinning_manager(self, fingerprints: Dict[str, str], domain: str):
        """Update the SSLCertificatePinningManager.swift file"""
        
        ssl_manager_path = self.ios_dir / "SSLCertificatePinningManager.swift"
        
        if not ssl_manager_path.exists():
            click.echo(f"⚠️ SSL Pinning Manager not found: {ssl_manager_path}")
            return False
        
        try:
            with open(ssl_manager_path, 'r') as f:
                content = f.read()
            
            # Find the setupDefaultConfigurations method
            setup_method_start = content.find("private func setupDefaultConfigurations() {")
            if setup_method_start == -1:
                click.echo("❌ Could not find setupDefaultConfigurations method")
                return False
            
            # Find the end of the production configuration section
            production_config_start = content.find("// Production Akash Network Configuration", setup_method_start)
            if production_config_start == -1:
                click.echo("⚠️ Production configuration section not found, adding new section")
                
                # Add production configuration before the staging configuration
                staging_config_start = content.find("// Staging Configuration", setup_method_start)
                if staging_config_start != -1:
                    new_config = f"""
        // Production Akash Network Configuration (Auto-updated)
        let akashProductionConfig = PinningConfiguration(
            domain: "{domain}",
            publicKeyHashes: Set([
                "{fingerprints.get('public_key_sha256', '')}",
                "{fingerprints.get('spki_sha256', '')}"
            ]),
            certificateHashes: Set([
                "{fingerprints.get('certificate_sha256', '')}"
            ]),
            allowSelfSigned: false,  // Production uses CA-signed certificates
            requireCertificatePinning: true,
            environment: .production
        )
        pinningConfigurations[akashProductionConfig.domain] = akashProductionConfig
        
        """
                    
                    content = content[:staging_config_start] + new_config + content[staging_config_start:]
                    
                    with open(ssl_manager_path, 'w') as f:
                        f.write(content)
                    
                    click.echo("✅ Added new production certificate pinning configuration")
                    return True
            else:
                # Update existing production configuration
                config_end = content.find("pinningConfigurations[akashProductionConfig.domain] = akashProductionConfig", production_config_start)
                if config_end != -1:
                    config_end = content.find("\n", config_end) + 1
                    
                    new_config = f"""        // Production Akash Network Configuration (Auto-updated)
        let akashProductionConfig = PinningConfiguration(
            domain: "{domain}",
            publicKeyHashes: Set([
                "{fingerprints.get('public_key_sha256', '')}",
                "{fingerprints.get('spki_sha256', '')}"
            ]),
            certificateHashes: Set([
                "{fingerprints.get('certificate_sha256', '')}"
            ]),
            allowSelfSigned: false,  // Production uses CA-signed certificates
            requireCertificatePinning: true,
            environment: .production
        )
        pinningConfigurations[akashProductionConfig.domain] = akashProductionConfig
"""
                    
                    content = content[:production_config_start] + new_config + content[config_end:]
                    
                    with open(ssl_manager_path, 'w') as f:
                        f.write(content)
                    
                    click.echo("✅ Updated production certificate pinning configuration")
                    return True
                    
        except Exception as e:
            click.echo(f"❌ Failed to update SSL Pinning Manager: {e}")
            return False
        
        return False

@click.command()
@click.option('--domain', default='omega-api.akash.network', help='Domain to update pinning for')
@click.option('--cert-path', help='Path to certificate file (optional)')
@click.option('--download', is_flag=True, help='Download certificate from domain')
def update_ios_pinning(domain, cert_path, download):
    """Update iOS certificate pinning with production certificates"""
    
    click.echo("🔐 Updating iOS Certificate Pinning Configuration")
    click.echo("=" * 60)
    
    updater = IOSCertificatePinningUpdater()
    
    # Determine certificate source
    if cert_path:
        cert_file = Path(cert_path)
        if not cert_file.exists():
            click.echo(f"❌ Certificate file not found: {cert_path}")
            return
        
        click.echo(f"📋 Using certificate file: {cert_path}")
        fingerprints = updater.extract_certificate_fingerprints(cert_path)
        
    elif download:
        click.echo(f"🌐 Downloading certificate from: {domain}")
        cert_der = updater.download_certificate_from_domain(domain)
        
        if cert_der:
            # Save certificate temporarily
            temp_cert_path = updater.ssl_dir / "temp_downloaded_cert.pem"
            cert = x509.load_der_x509_certificate(cert_der)
            cert_pem = cert.public_bytes(serialization.Encoding.PEM)
            
            with open(temp_cert_path, 'wb') as f:
                f.write(cert_pem)
            
            fingerprints = updater.extract_certificate_fingerprints(str(temp_cert_path))
            
            # Clean up temp file
            temp_cert_path.unlink()
        else:
            click.echo("❌ Failed to download certificate")
            return
    else:
        # Use local SSL certificate
        ssl_cert_path = updater.ssl_dir / "cert.pem"
        if not ssl_cert_path.exists():
            click.echo(f"❌ Local SSL certificate not found: {ssl_cert_path}")
            click.echo("   Run the SSL certificate generation first")
            return
        
        click.echo(f"📋 Using local certificate: {ssl_cert_path}")
        fingerprints = updater.extract_certificate_fingerprints(str(ssl_cert_path))
    
    if not fingerprints:
        click.echo("❌ Failed to extract certificate fingerprints")
        return
    
    # Display fingerprints
    click.echo(f"\n🔗 Certificate Fingerprints for {domain}:")
    for fp_type, fp_value in fingerprints.items():
        click.echo(f"   {fp_type}: {fp_value}")
    
    # Update iOS pinning configuration
    click.echo(f"\n🔧 Updating iOS SSL Pinning Manager...")
    
    if updater.update_ssl_pinning_manager(fingerprints, domain):
        click.echo("✅ iOS certificate pinning updated successfully")
        
        # Generate Swift code for manual verification
        swift_code = updater.generate_swift_pinning_code(fingerprints, domain)
        
        swift_output_path = updater.ios_dir / "ProductionCertificatePinning.swift"
        with open(swift_output_path, 'w') as f:
            f.write(swift_code)
        
        click.echo(f"📝 Generated Swift code: {swift_output_path}")
        
        click.echo(f"\n🎯 Next Steps:")
        click.echo(f"   1. Build and test the iOS app with new pinning configuration")
        click.echo(f"   2. Verify SSL connections work correctly")
        click.echo(f"   3. Test certificate validation in different environments")
        click.echo(f"   4. Deploy to TestFlight for testing")
        
    else:
        click.echo("❌ Failed to update iOS certificate pinning")
    
    click.echo("=" * 60)

if __name__ == '__main__':
    update_ios_pinning()