# OMEGA API Environment Configuration
# Generated by Terraform - DO NOT EDIT MANUALLY

# Environment
OMEGA_ENV=${environment}
NODE_ENV=${environment}
FLASK_ENV=${environment}

# API Configuration
PORT=${api_port}
HOST=0.0.0.0
SECRET_KEY=${secret_key}

# Redis Configuration
REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}
REDIS_PASSWORD=${redis_password}
REDIS_URL=redis://:${redis_password}@${redis_host}:${redis_port}/0

# Database Configuration
%{ if database_url != "" ~}
DATABASE_URL=${database_url}
%{ endif ~}

# Security
CORS_ORIGINS=*
CSRF_ENABLED=true
SESSION_COOKIE_SECURE=true
SESSION_COOKIE_HTTPONLY=true
SESSION_COOKIE_SAMESITE=Lax

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
ENABLE_REQUEST_LOGGING=true

# Performance
WORKER_PROCESSES=4
WORKER_TIMEOUT=300
MAX_REQUESTS=1000
MAX_REQUESTS_JITTER=100

# ML Models
MODEL_PATH=/app/models
CACHE_MODEL_PREDICTIONS=true
MODEL_WARMUP_ENABLED=true

# API Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60
RATE_LIMIT_BURST=10

# Monitoring
METRICS_ENABLED=true
HEALTH_CHECK_ENABLED=true
PROMETHEUS_METRICS=true

# Features
ENABLE_ASYNC_PROCESSING=true
ENABLE_PREDICTION_CACHING=true
ENABLE_BATCH_PREDICTIONS=true

# Timeouts
REQUEST_TIMEOUT=60
PREDICTION_TIMEOUT=120
DATABASE_TIMEOUT=30

# SSL/TLS
SSL_ENABLED=true
SSL_CERT_PATH=/app/ssl/cert.pem
SSL_KEY_PATH=/app/ssl/key.pem